name: Hourly Useless Commit

on:
  schedule:
    # All January dates + Feb 1
    - cron: '0 12 5-12,15,18-19,22,25-26,29 1 *'
    - cron: '0 12 1 2 *'
jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure git
        run: |
          git config user.name "Jens Schäfer"
          git config user.email "jens-schaefer@outlook.com"

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..5}; do
            echo "Making commit #$i"
            echo "Last updated: $(date)" > useless.txt
            git add useless.txt
            git commit -m "Useless commit #$i: $(date)"
            git push
            sleep 1 # Optional: avoid race conditions in case of rapid commits
          done
